server:
  port: 8083
swagger:
  title: Vehicle Tax Service
  version: 1.0
  description: An example Vehicle Tax Spring Boot microservice.
  contact:
    name: Developer Bloke
    url: http://www.devbloke.me.uk/
    email: this.will.bounce@devbloke.me.uk
  license:
    type: License Type
    url: http://license.url/
  regex: /api/.*
  tos:
    url: http://termsofservice.url/
    