swagger:
  title: Spring Boot Solid
  description: An example Spring Boot Solid microservice written in Java.
  version: 1.0
  contact:
    name: Martin Ingram
    url: http://www.martiningram.uk/
    email: this.will.bounce@devbloke.me.uk

springdoc:
  swagger-ui:
    path: /swagger-ui.html
