version: "3.8"

services:

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbuser
      MONGO_INITDB_ROOT_PASSWORD: userpass
      MONGO_INITDB_DATABASE: examples
    ports:
      - 27017:27017
    volumes:
      - ./src/main/mongodb:/docker-entrypoint-initdb.d
