swagger:
  title: Kotlin & Spring Boot with ElasticSearch
  version: 1.0
  description: An example Spring Boot / ElasticSearch microservice written in Kotlin.
  regex: /api/.*
  contact:
    name: Martin Ingram
    url: http://www.martiningram.uk/
    email: this.will.bounce@devbloke.me.uk

elasticsearch:
  endpoint: localhost:9200