swagger:
  title: Kotlin & Spring Boot Example
  version: 1.0
  description: An example Spring Boot microservice written in Kotlin.
  regex: /api/.*
  contact:
    name: Martin Ingram
    url: http://www.martiningram.uk/
    email: this.will.bounce@devbloke.me.uk
