server:
  port: 8081
  
spring:
  kafka:
    consumer:
      group-id: example-consumer
      bootstrap-servers: localhost:9092
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties.spring.json.trusted.packages: com.meridal.examples.domain

messaging:
  listener:
    topic: examples

service:
  title: Example Spring Boot Kafka Subscriber
  description: A simple microservice that subscribes to a Kafka topic.
  api:
    endpoint: /api/.*
    version: 1.0
    status: live
  contact:
    name: Martin Ingram
    url: https://github.com/dev-bloke
    email: dev.bloke@devbloke.me.uk
  licence:
    type: License Type
    url: http://license.url/
    tos: http://termsofservice.url/