swagger:
  title: Twitter Proxy
  description: An example Spring Boot Twitter Proxy written in Java.
  version: 1.0
  contact:
    name: Martin Ingram
    url: http://www.martiningram.uk/
    email: this.will.bounce@devbloke.me.uk

springdoc:
  swagger-ui:
    path: /swagger-ui.html

api2:
  baseUrl: https://api.twitter.com/2/users/
  authorization: Bearer AAAAAAAAAAAAAAAAAAAAAFJ2jgEAAAAAmRK2DTJNTCb2gvrEE5VVgfPbP9E%3DvJk3YBuR3unSf6JOyz6kUkmWbw2IVqRqnudjBHPiet0izw4jqX