# Version 0.0.1
FROM ubuntu:latest
MAINTAINER Martin Ingram "dev.bloke@devbloke.me.uk"
RUN apt-get update && apt-get install -y nginx
RUN echo 'Hello from Docker World' > /usr/share/nginx/html/index.html
EXPOSE 80