swagger:
  title: Spring Boot MongoDB
  version: 1.0
  description: An example Spring Boot microservice with MongoDB persistence.
  regex: /api/.*
  contact:
    name: Developer Bloke
    url: http://www.devbloke.me.uk/
    email: this.will.bounce@devbloke.me.uk
  license:
    type: License Type
    url: http://license.url/
  tos:
    url: http://termsofservice.url/

mongodb:
  database: examples
  uri: mongodb://localhost:27017
