spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
      
messaging:
  queue: example-queue

swagger:
  title: Kotlin Spring Boot RabbitMQ Publisher
  description: An example Spring Boot microservice written in Kotlin that publishes to RabbitMQ.
  version: 1.0
  regex: /api/.*
  contact:
    name: Martin Ingram
    url: http://www.martiningram.uk/
    email: this.will.bounce@devbloke.me.uk