swagger:
  title: Kotlin & Spring Boot with MongoDB
  version: 1.0
  description: An example Spring Boot / MongoDB microservice written in Kotlin.
  regex: /api/.*
  contact:
    name: Martin Ingram
    url: http://www.martiningram.uk/
    email: this.will.bounce@devbloke.me.uk

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: examples
      username: dbuser
      password: userpass