rootProject.name = "kotlin-parent"
include("kotlin-basics")
include("kotlin-domain")
include("kotlin-spring-boot")
include("kotlin-spring-boot-dynamodb")
include("kotlin-spring-boot-elasticsearch")
include("kotlin-spring-boot-mongodb")
include("kotlin-spring-boot-mysql")
include("kotlin-spring-boot-rabbitmq-publisher")
include("kotlin-spring-boot-rabbitmq-subscriber")
