swagger:
  title: Java Spring Boot MySQL
  description: An example Spring Boot microservice written in Java with MySQL persistence.
  version: 1.0
  regex: /api/.*
  contact:
    name: Martin Ingram
    url: http://www.martiningram.uk/
    email: this.will.bounce@devbloke.me.uk

spring:
  datasource:
    url: jdbc:mysql://localhost/userdb
    username: dbuser
    password: userpass
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate.ddl-auto: none
    hibernate.connection.useSSL: false
    hibernate.connection.requireSSL: false