swagger:
  contact:
    name: Martin Ingram
    url: http://www.martiningram.uk/
    email: this.will.bounce@devbloke.me.uk
  description: An example Spring Boot microservice written in Java with MySQL persistence.
  license:
    type: License Type
    url: http://license.url/
  regex: /api/.*
  tos:
    url: http://termsofservice.url/
  title: Spring Boot MySQL
  version: 1.0

spring:
  datasource:
    url: jdbc:mysql://localhost/userdb?useSSL:false&requireSSL:false
    username: dbuser
    password: userpass
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate.ddl-auto: none